// Outline set
export {
  Bars3Icon,
  XMarkIcon,
  UserCircleIcon,
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  ArrowRightCircleIcon,
  BoltIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BuildingStorefrontIcon,
  BuildingOffice2Icon,
  BuildingOfficeIcon,
  CalendarDaysIcon,
  CameraIcon,
  ChartPieIcon,
  ChatBubbleLeftRightIcon,
  ClipboardDocumentCheckIcon,
  CloudIcon,
  CodeBracketIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  CubeIcon,
  CurrencyDollarIcon,
  DevicePhoneMobileIcon,
  DocumentCheckIcon,
  EnvelopeIcon,
  FingerPrintIcon,
  FlagIcon,
  GiftIcon,
  HeartIcon,
  HomeModernIcon,
  KeyIcon,
  LifebuoyIcon,
  LightBulbIcon,
  MegaphoneIcon,
  MusicalNoteIcon,
  NewspaperIcon,
  PaintBrushIcon,
  PhotoIcon,
  PlayCircleIcon,
  PresentationChartLineIcon,
  ShieldCheckIcon,
  SparklesIcon,
  Square3Stack3DIcon,
  Squares2X2Icon,
  SwatchIcon,
  TagIcon,
  TicketIcon,
  TruckIcon,
  UserGroupIcon,
  WalletIcon,
  WrenchScrewdriverIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
} from "@heroicons/react/24/outline";

// Solid set
export {
  CheckCircleIcon,
  ExclamationTriangleIcon,
  InformationCircleIcon,
  MagnifyingGlassIcon,
  StarIcon,
  ArrowRightIcon,
  PlusCircleIcon,
  MapPinIcon,
  PhoneIcon,
  GlobeAltIcon,
} from "@heroicons/react/24/solid";
